version: '3'
services:
  dockerapp:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - redis
    networks:
      - my_net
  redis:
    image: redis:latest    
    networks:
      - my_net
networks:
  my_net:
    driver: bridge    