name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
env:  
  DOCKER_REPO_NAME: burki169
jobs:

  build:

    runs-on: ubuntu-latest

    steps:    
    - uses: actions/checkout@v3
    
    - name: Set docker image tag
      run: |
         echo "COMMIT_ID=$GITHUB_SHA" >> $GITHUB_ENV
         
    - name: Test commit Id
      run: |
        echo $COMMIT_ID
    
    - name: Build the Docker image
      run: |
        echo $IMAGE_TAG
        docker build . --file Dockerfile --tag $IMAGE_TAG
    
    - name: Publish the Docker image
      run: |                
        docker login --username=${{ secrets.DOCKER_HUB_USER }} --password=${{ secrets.DOCKER_HUB_TOKEN }}
        docker image push $DOCKER_REPO_NAME/$IMAGE_TAG
        docker logout
