name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
env:  
  DOCKER_REPO_NAME: burki169
  DOCKER_IMAGE_BASE_NAME: docker-playground
jobs:

  build:

    runs-on: ubuntu-latest

    steps:    
    - uses: actions/checkout@v3
    
    - name: Get commit Id
      run: |
         echo "COMMIT_ID=$GITHUB_SHA" >> $GITHUB_ENV                    
         
    - name: Set image id
      run: |
         echo "DOCKER_IMAGE_TAG=$DOCKER_REPO_NAME/$DOCKER_IMAGE_BASE_NAME:$COMMIT_ID" >> $GITHUB_ENV                    
    
    - name: Build the Docker image
      run: |
        echo $IMAGE_TAG
        docker build . --file Dockerfile --tag $DOCKER_IMAGE_TAG
    
    - name: Publish the Docker image
      run: |                
        docker login --username=${{ secrets.DOCKER_HUB_USER }} --password=${{ secrets.DOCKER_HUB_TOKEN }}
        docker image push $DOCKER_IMAGE_TAG
        docker logout
