name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag docker-playground:$(date +%s)
    
    - name: Publish the Docker image
      env: 
        DOCKER_USER: ${{ secrets.DOCKER_HUB_USER }}
      run: |
        echo '------'
        echo 'user is: $DOCKER_USER'
        docker login --username=${{ secrets.DOCKER_HUB_USER }} --password=${{ secrets.DOCKER_HUB_TOKEN }}
        docker image push $DOCKER_USER/docker-playground:$(date +%s)
        docker logout
